### ISSUE TITLE
Feature: Allow for overriding the bundle method.

### ISSUE THREAD

**Issue by joshuairl** [Vestorly/ember-cli-deploy-versioning#2]
First off, love this - thank you so much for your hard work.

I was thinking about submitting a pull request with an easily overridden bundler method so I can produce custom builds since I'm doing different OTT Smart TV platform builds of the same app with different pieces, some of them require firing off a shell command to build, etc... would be cool to have them tied into this with a custom method.

I'm thinking this would be the perfect place to do it.

Instead of a zip, I may end up with an IPK for instance.

Would you support this type of enhancement? or should I build a separate plugin you think?

**Comment by Gaurav0** [comment]
Hi, @joshuairl I think we here at Vestory would welcome this sort of enhancement only so long as it has little performance impact and came with good tests. Thank you!

**Comment by joebartels** [comment]
Closing - looking forward to any enhancements that come this way.

Sounds like you're on the right track and so if you're only interested in taking advantage of the `willUpload` hook - which does do some extra work to create a `zip` of the project then you could certainly modify the code to accept a custom `bundler` function (as you suggested)
*vs.* the hard coded bundler:
https://github.com/Vestorly/ember-cli-deploy-versioning/blob/master/index.js#L184

I'd suggest following the pattern that allows for a configurable `versioner`, `incrementer`, and `formatter`:
https://github.com/Vestorly/ember-cli-deploy-versioning/blob/master/index.js#L60
